namespace Emby.Plugins.InitMetaData
{
    public class StudioRule
    {
        public static string[][] Rule = new string[][]
        {
            new string[] { @"DMHY", "動漫花園" },
            new string[] { @"DMG" , "動漫國字幕組"},
            new string[] { @"NC-Raws", "NC-Raws"},
            new string[] { @"kissaten", "喵萌奶茶屋"},
            new string[] { @"Lilith-Raws", "Lilith-Raws"},
            new string[] { @"MagicStar", "魔星字幕团"},
            new string[] { @"Sakurato", "桜都字幕组"},
            new string[] { @"Skymoon-Raws", "天月動漫&發佈組"},
            new string[] { @"KTXP", "极影字幕社"},
            new string[] { @"LoliHouse", "LoliHouse"},
            new string[] { @"SumiSora", "澄空學園"},
            new string[] { @"HYSUB", "幻樱字幕组"},
            new string[] { @"Comicat", "漫貓字幕社"},
            new string[] { @"Romanticat", "貓戀漢化組"},
            new string[] { @"Airota", "千夏字幕組"},
            new string[] { @"UHA-WINGS", "悠哈C9字幕社"},
            new string[] { @"CoolComic404", "酷漫404"},
            new string[] { @"Kamigami", "诸神字幕组"},
            new string[] { @"STYHSub", "霜庭云花Sub"},
            new string[] { @"GM-Team", "GM-Team"},
            new string[] { @"FLsnow", "雪飘工作室"},
            new string[] { @"MCE", "MCE漢化組"},
            new string[] { @"Marukazoku", "丸子家族"},
            new string[] { @"XKsub", "星空字幕組"},
            new string[] { @"梦蓝字幕组", "夢藍字幕組"},
            new string[] { @"AngelEcho", "LoveEcho!"},
            new string[] { @"SweetSub", "SweetSub"},
            new string[] { @"FYSub", "枫叶字幕组"},
            new string[] { @"Haruhana", "撥雪尋春"},
            new string[] { @"LKSUB", "輕之國度字幕組"},
            new string[] { @"云光字幕组", "雲光字幕組"},
            new string[] { @"BeanSub", "豌豆字幕组"},
            new string[] { @"zhong ken", "中肯字幕組"},
            new string[] { @"SWSUB", "SW字幕組"},
            new string[] { @"SBSUB", "银色子弹字幕组"},
            new string[] { @"Kamigami", "諸神"},
            new string[] { @"BeanSub", "豌豆"},
            new string[] { @"FZSD", "風之聖殿"},
            new string[] { @"YWCN", "YWCN字幕组"},
            new string[] { @"CASO", "華盟字幕社"},
            new string[] { @"PCSUB", "波洛咖啡廳"},
            new string[] { @"Dymy", "動音漫影"},
            new string[] { @"VCB-Studio", "VCB-Studio"},
            new string[] { @"KRL", "KRL字幕組"},
            new string[] { @"DHR", "DHR動研字幕組"},
            new string[] { @"MakariHoshiyume", "茉語星夢"},
            new string[] { @"FatCatRAW", "肥貓壓制"},
            new string[] { @"SC-OL", "雪酷字幕組"},
            new string[] { @"LittleSubs", "Little字幕组"},
            new string[] { @"AI-Raws", "AI-Raws"},
            new string[] { @"LPSub", "離譜Sub"},
            new string[] { @"APTX4869", "柯南事務所"},
            new string[] { @"冷番补完字幕组", "冷番補完字幕組"},
            new string[] { @"igsub", "愛咕字幕組"},
            new string[] { @"KyokuSai", "極彩字幕组"},
            new string[] { @"AQUAWS", "AQUA工作室"},
            new string[] { @"Todokoi", "屆戀字幕組"},
            new string[] { @"夜莺家族", "夜鶯家族"},
            new string[] { @"MHLY", "夢幻戀櫻字幕組"},
            new string[] { @"LPSub", "WBX-SUB"},
            new string[] { @"MingY", "MingY"},
            new string[] { @"Billion Meta Lab", "億次研同好會"},
            new string[] { @"黑岩射手吧字幕组", "黑岩射手吧字幕组"},
            new string[] { @"ANi", "ANi"},
        };
    }
}
